name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - staging
    tags:
      - 'v*.*' # Example: v1.0 to trigger production deployment
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build:
    runs-on: ubuntu-latest
    needs: run_tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the application
        run: |
          echo "Building the application for deployment"

  deploy_staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Staging (Simulated)
        run: |
          echo "Simulating deployment to staging environment"

  deploy_production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (Simulated)
        run: |
          echo "Simulating deployment to production environment"
